# location of the files used for the migrations
migrations: sample/migrations
checkpoint: sample/migrations/checkpoint.txt

# Folder of the source files
source: sample/source

# Target folder of the processed files. Set this to the same as 'source' to overwrite
target: sample/target

